pub static MAP: phf::Map<&'static [u8], unsafe fn(*mut JSContext, HandleObject)> = ::phf::Map {
    key: 1897749892740154578,
    disps: ::phf::Slice::Static(&[
        (0, 31),
        (0, 1),
        (0, 16),
        (1, 142),
        (0, 4),
        (0, 118),
        (0, 56),
        (0, 9),
        (1, 13),
        (5, 256),
        (1, 169),
        (0, 10),
        (1, 5),
        (5, 162),
        (0, 184),
        (0, 14),
        (0, 0),
        (0, 130),
        (0, 9),
        (2, 86),
        (1, 255),
        (0, 28),
        (0, 55),
        (0, 21),
        (0, 34),
        (0, 146),
        (1, 21),
        (1, 0),
        (0, 1),
        (3, 92),
        (0, 52),
        (0, 0),
        (0, 150),
        (0, 26),
        (0, 225),
        (1, 17),
        (1, 92),
        (0, 6),
        (1, 28),
        (0, 17),
        (1, 2),
        (0, 245),
        (0, 199),
        (3, 205),
        (0, 17),
        (0, 182),
        (19, 26),
        (0, 68),
        (5, 239),
        (15, 181),
        (86, 236),
        (2, 145),
        (9, 199),
    ]),
    entries: ::phf::Slice::Static(&[
        (b"CharacterData" as &'static [u8], codegen::Bindings::CharacterDataBinding::CharacterDataBinding::DefineDOMInterface),
        (b"HTMLAudioElement" as &'static [u8], codegen::Bindings::HTMLAudioElementBinding::HTMLAudioElementBinding::DefineDOMInterface),
        (b"CloseEvent" as &'static [u8], codegen::Bindings::CloseEventBinding::CloseEventBinding::DefineDOMInterface),
        (b"BluetoothDevice" as &'static [u8], codegen::Bindings::BluetoothDeviceBinding::BluetoothDeviceBinding::DefineDOMInterface),
        (b"BluetoothAdvertisingEvent" as &'static [u8], codegen::Bindings::BluetoothAdvertisingEventBinding::BluetoothAdvertisingEventBinding::DefineDOMInterface),
        (b"Permissions" as &'static [u8], codegen::Bindings::PermissionsBinding::PermissionsBinding::DefineDOMInterface),
        (b"HTMLHeadingElement" as &'static [u8], codegen::Bindings::HTMLHeadingElementBinding::HTMLHeadingElementBinding::DefineDOMInterface),
        (b"HTMLEmbedElement" as &'static [u8], codegen::Bindings::HTMLEmbedElementBinding::HTMLEmbedElementBinding::DefineDOMInterface),
        (b"HTMLObjectElement" as &'static [u8], codegen::Bindings::HTMLObjectElementBinding::HTMLObjectElementBinding::DefineDOMInterface),
        (b"ErrorEvent" as &'static [u8], codegen::Bindings::ErrorEventBinding::ErrorEventBinding::DefineDOMInterface),
        (b"MediaQueryList" as &'static [u8], codegen::Bindings::MediaQueryListBinding::MediaQueryListBinding::DefineDOMInterface),
        (b"WebGLRenderbuffer" as &'static [u8], codegen::Bindings::WebGLRenderbufferBinding::WebGLRenderbufferBinding::DefineDOMInterface),
        (b"MediaList" as &'static [u8], codegen::Bindings::MediaListBinding::MediaListBinding::DefineDOMInterface),
        (b"FileReader" as &'static [u8], codegen::Bindings::FileReaderBinding::FileReaderBinding::DefineDOMInterface),
        (b"HTMLDivElement" as &'static [u8], codegen::Bindings::HTMLDivElementBinding::HTMLDivElementBinding::DefineDOMInterface),
        (b"Crypto" as &'static [u8], codegen::Bindings::CryptoBinding::CryptoBinding::DefineDOMInterface),
        (b"Screen" as &'static [u8], codegen::Bindings::ScreenBinding::ScreenBinding::DefineDOMInterface),
        (b"HTMLAreaElement" as &'static [u8], codegen::Bindings::HTMLAreaElementBinding::HTMLAreaElementBinding::DefineDOMInterface),
        (b"HTMLCollection" as &'static [u8], codegen::Bindings::HTMLCollectionBinding::HTMLCollectionBinding::DefineDOMInterface),
        (b"ExtendableEvent" as &'static [u8], codegen::Bindings::ExtendableEventBinding::ExtendableEventBinding::DefineDOMInterface),
        (b"PerformanceObserverEntryList" as &'static [u8], codegen::Bindings::PerformanceObserverEntryListBinding::PerformanceObserverEntryListBinding::DefineDOMInterface),
        (b"HTMLAnchorElement" as &'static [u8], codegen::Bindings::HTMLAnchorElementBinding::HTMLAnchorElementBinding::DefineDOMInterface),
        (b"Headers" as &'static [u8], codegen::Bindings::HeadersBinding::HeadersBinding::DefineDOMInterface),
        (b"WebGL2RenderingContext" as &'static [u8], codegen::Bindings::WebGL2RenderingContextBinding::WebGL2RenderingContextBinding::DefineDOMInterface),
        (b"NodeList" as &'static [u8], codegen::Bindings::NodeListBinding::NodeListBinding::DefineDOMInterface),
        (b"Touch" as &'static [u8], codegen::Bindings::TouchBinding::TouchBinding::DefineDOMInterface),
        (b"HTMLMediaElement" as &'static [u8], codegen::Bindings::HTMLMediaElementBinding::HTMLMediaElementBinding::DefineDOMInterface),
        (b"HTMLInputElement" as &'static [u8], codegen::Bindings::HTMLInputElementBinding::HTMLInputElementBinding::DefineDOMInterface),
        (b"DocumentFragment" as &'static [u8], codegen::Bindings::DocumentFragmentBinding::DocumentFragmentBinding::DefineDOMInterface),
        (b"Bluetooth" as &'static [u8], codegen::Bindings::BluetoothBinding::BluetoothBinding::DefineDOMInterface),
        (b"XMLHttpRequestUpload" as &'static [u8], codegen::Bindings::XMLHttpRequestUploadBinding::XMLHttpRequestUploadBinding::DefineDOMInterface),
        (b"DOMTokenList" as &'static [u8], codegen::Bindings::DOMTokenListBinding::DOMTokenListBinding::DefineDOMInterface),
        (b"ServiceWorkerContainer" as &'static [u8], codegen::Bindings::ServiceWorkerContainerBinding::ServiceWorkerContainerBinding::DefineDOMInterface),
        (b"CSSConditionRule" as &'static [u8], codegen::Bindings::CSSConditionRuleBinding::CSSConditionRuleBinding::DefineDOMInterface),
        (b"SVGGraphicsElement" as &'static [u8], codegen::Bindings::SVGGraphicsElementBinding::SVGGraphicsElementBinding::DefineDOMInterface),
        (b"PerformancePaintTiming" as &'static [u8], codegen::Bindings::PerformancePaintTimingBinding::PerformancePaintTimingBinding::DefineDOMInterface),
        (b"HTMLFormControlsCollection" as &'static [u8], codegen::Bindings::HTMLFormControlsCollectionBinding::HTMLFormControlsCollectionBinding::DefineDOMInterface),
        (b"HTMLLIElement" as &'static [u8], codegen::Bindings::HTMLLIElementBinding::HTMLLIElementBinding::DefineDOMInterface),
        (b"HTMLVideoElement" as &'static [u8], codegen::Bindings::HTMLVideoElementBinding::HTMLVideoElementBinding::DefineDOMInterface),
        (b"DOMQuad" as &'static [u8], codegen::Bindings::DOMQuadBinding::DOMQuadBinding::DefineDOMInterface),
        (b"VRFieldOfView" as &'static [u8], codegen::Bindings::VRFieldOfViewBinding::VRFieldOfViewBinding::DefineDOMInterface),
        (b"HTMLSpanElement" as &'static [u8], codegen::Bindings::HTMLSpanElementBinding::HTMLSpanElementBinding::DefineDOMInterface),
        (b"VRDisplay" as &'static [u8], codegen::Bindings::VRDisplayBinding::VRDisplayBinding::DefineDOMInterface),
        (b"CSS" as &'static [u8], codegen::Bindings::CSSBinding::CSSBinding::DefineDOMInterface),
        (b"CSSMediaRule" as &'static [u8], codegen::Bindings::CSSMediaRuleBinding::CSSMediaRuleBinding::DefineDOMInterface),
        (b"CustomElementRegistry" as &'static [u8], codegen::Bindings::CustomElementRegistryBinding::CustomElementRegistryBinding::DefineDOMInterface),
        (b"TestRunner" as &'static [u8], codegen::Bindings::TestRunnerBinding::TestRunnerBinding::DefineDOMInterface),
        (b"CanvasPattern" as &'static [u8], codegen::Bindings::CanvasPatternBinding::CanvasPatternBinding::DefineDOMInterface),
        (b"WebSocket" as &'static [u8], codegen::Bindings::WebSocketBinding::WebSocketBinding::DefineDOMInterface),
        (b"HTMLUListElement" as &'static [u8], codegen::Bindings::HTMLUListElementBinding::HTMLUListElementBinding::DefineDOMInterface),
        (b"HTMLBodyElement" as &'static [u8], codegen::Bindings::HTMLBodyElementBinding::HTMLBodyElementBinding::DefineDOMInterface),
        (b"PluginArray" as &'static [u8], codegen::Bindings::PluginArrayBinding::PluginArrayBinding::DefineDOMInterface),
        (b"File" as &'static [u8], codegen::Bindings::FileBinding::FileBinding::DefineDOMInterface),
        (b"CSSStyleSheet" as &'static [u8], codegen::Bindings::CSSStyleSheetBinding::CSSStyleSheetBinding::DefineDOMInterface),
        (b"TestBindingIterable" as &'static [u8], codegen::Bindings::TestBindingIterableBinding::TestBindingIterableBinding::DefineDOMInterface),
        (b"HTMLIFrameElement" as &'static [u8], codegen::Bindings::HTMLIFrameElementBinding::HTMLIFrameElementBinding::DefineDOMInterface),
        (b"GamepadButtonList" as &'static [u8], codegen::Bindings::GamepadButtonListBinding::GamepadButtonListBinding::DefineDOMInterface),
        (b"TestWorkletGlobalScope" as &'static [u8], codegen::Bindings::TestWorkletGlobalScopeBinding::TestWorkletGlobalScopeBinding::DefineDOMInterface),
        (b"CSSKeyframesRule" as &'static [u8], codegen::Bindings::CSSKeyframesRuleBinding::CSSKeyframesRuleBinding::DefineDOMInterface),
        (b"HTMLTableSectionElement" as &'static [u8], codegen::Bindings::HTMLTableSectionElementBinding::HTMLTableSectionElementBinding::DefineDOMInterface),
        (b"PerformanceObserver" as &'static [u8], codegen::Bindings::PerformanceObserverBinding::PerformanceObserverBinding::DefineDOMInterface),
        (b"WebGLShader" as &'static [u8], codegen::Bindings::WebGLShaderBinding::WebGLShaderBinding::DefineDOMInterface),
        (b"HTMLDetailsElement" as &'static [u8], codegen::Bindings::HTMLDetailsElementBinding::HTMLDetailsElementBinding::DefineDOMInterface),
        (b"HTMLCanvasElement" as &'static [u8], codegen::Bindings::HTMLCanvasElementBinding::HTMLCanvasElementBinding::DefineDOMInterface),
        (b"WebGLRenderingContext" as &'static [u8], codegen::Bindings::WebGLRenderingContextBinding::WebGLRenderingContextBinding::DefineDOMInterface),
        (b"HTMLLabelElement" as &'static [u8], codegen::Bindings::HTMLLabelElementBinding::HTMLLabelElementBinding::DefineDOMInterface),
        (b"CSSSupportsRule" as &'static [u8], codegen::Bindings::CSSSupportsRuleBinding::CSSSupportsRuleBinding::DefineDOMInterface),
        (b"PaintWorkletGlobalScope" as &'static [u8], codegen::Bindings::PaintWorkletGlobalScopeBinding::PaintWorkletGlobalScopeBinding::DefineDOMInterface),
        (b"MouseEvent" as &'static [u8], codegen::Bindings::MouseEventBinding::MouseEventBinding::DefineDOMInterface),
        (b"TouchList" as &'static [u8], codegen::Bindings::TouchListBinding::TouchListBinding::DefineDOMInterface),
        (b"MutationRecord" as &'static [u8], codegen::Bindings::MutationRecordBinding::MutationRecordBinding::DefineDOMInterface),
        (b"KeyboardEvent" as &'static [u8], codegen::Bindings::KeyboardEventBinding::KeyboardEventBinding::DefineDOMInterface),
        (b"MimeType" as &'static [u8], codegen::Bindings::MimeTypeBinding::MimeTypeBinding::DefineDOMInterface),
        (b"BluetoothRemoteGATTServer" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTServerBinding::BluetoothRemoteGATTServerBinding::DefineDOMInterface),
        (b"PerformanceTiming" as &'static [u8], codegen::Bindings::PerformanceTimingBinding::PerformanceTimingBinding::DefineDOMInterface),
        (b"HTMLOptionElement" as &'static [u8], codegen::Bindings::HTMLOptionElementBinding::HTMLOptionElementBinding::DefineDOMInterface),
        (b"MediaError" as &'static [u8], codegen::Bindings::MediaErrorBinding::MediaErrorBinding::DefineDOMInterface),
        (b"HTMLDirectoryElement" as &'static [u8], codegen::Bindings::HTMLDirectoryElementBinding::HTMLDirectoryElementBinding::DefineDOMInterface),
        (b"WebGLProgram" as &'static [u8], codegen::Bindings::WebGLProgramBinding::WebGLProgramBinding::DefineDOMInterface),
        (b"FileList" as &'static [u8], codegen::Bindings::FileListBinding::FileListBinding::DefineDOMInterface),
        (b"HTMLDataListElement" as &'static [u8], codegen::Bindings::HTMLDataListElementBinding::HTMLDataListElementBinding::DefineDOMInterface),
        (b"StyleSheetList" as &'static [u8], codegen::Bindings::StyleSheetListBinding::StyleSheetListBinding::DefineDOMInterface),
        (b"CustomEvent" as &'static [u8], codegen::Bindings::CustomEventBinding::CustomEventBinding::DefineDOMInterface),
        (b"HTMLTableCaptionElement" as &'static [u8], codegen::Bindings::HTMLTableCaptionElementBinding::HTMLTableCaptionElementBinding::DefineDOMInterface),
        (b"DOMMatrixReadOnly" as &'static [u8], codegen::Bindings::DOMMatrixReadOnlyBinding::DOMMatrixReadOnlyBinding::DefineDOMInterface),
        (b"PaintSize" as &'static [u8], codegen::Bindings::PaintSizeBinding::PaintSizeBinding::DefineDOMInterface),
        (b"Attr" as &'static [u8], codegen::Bindings::AttrBinding::AttrBinding::DefineDOMInterface),
        (b"MutationObserver" as &'static [u8], codegen::Bindings::MutationObserverBinding::MutationObserverBinding::DefineDOMInterface),
        (b"WebGLObject" as &'static [u8], codegen::Bindings::WebGLObjectBinding::WebGLObjectBinding::DefineDOMInterface),
        (b"SVGElement" as &'static [u8], codegen::Bindings::SVGElementBinding::SVGElementBinding::DefineDOMInterface),
        (b"HTMLTitleElement" as &'static [u8], codegen::Bindings::HTMLTitleElementBinding::HTMLTitleElementBinding::DefineDOMInterface),
        (b"PopStateEvent" as &'static [u8], codegen::Bindings::PopStateEventBinding::PopStateEventBinding::DefineDOMInterface),
        (b"ProcessingInstruction" as &'static [u8], codegen::Bindings::ProcessingInstructionBinding::ProcessingInstructionBinding::DefineDOMInterface),
        (b"HTMLTextAreaElement" as &'static [u8], codegen::Bindings::HTMLTextAreaElementBinding::HTMLTextAreaElementBinding::DefineDOMInterface),
        (b"HTMLScriptElement" as &'static [u8], codegen::Bindings::HTMLScriptElementBinding::HTMLScriptElementBinding::DefineDOMInterface),
        (b"HTMLModElement" as &'static [u8], codegen::Bindings::HTMLModElementBinding::HTMLModElementBinding::DefineDOMInterface),
        (b"Request" as &'static [u8], codegen::Bindings::RequestBinding::RequestBinding::DefineDOMInterface),
        (b"HTMLHtmlElement" as &'static [u8], codegen::Bindings::HTMLHtmlElementBinding::HTMLHtmlElementBinding::DefineDOMInterface),
        (b"HTMLDataElement" as &'static [u8], codegen::Bindings::HTMLDataElementBinding::HTMLDataElementBinding::DefineDOMInterface),
        (b"HTMLFieldSetElement" as &'static [u8], codegen::Bindings::HTMLFieldSetElementBinding::HTMLFieldSetElementBinding::DefineDOMInterface),
        (b"HTMLMapElement" as &'static [u8], codegen::Bindings::HTMLMapElementBinding::HTMLMapElementBinding::DefineDOMInterface),
        (b"NamedNodeMap" as &'static [u8], codegen::Bindings::NamedNodeMapBinding::NamedNodeMapBinding::DefineDOMInterface),
        (b"TextEncoder" as &'static [u8], codegen::Bindings::TextEncoderBinding::TextEncoderBinding::DefineDOMInterface),
        (b"TouchEvent" as &'static [u8], codegen::Bindings::TouchEventBinding::TouchEventBinding::DefineDOMInterface),
        (b"WebGLTexture" as &'static [u8], codegen::Bindings::WebGLTextureBinding::WebGLTextureBinding::DefineDOMInterface),
        (b"HTMLDialogElement" as &'static [u8], codegen::Bindings::HTMLDialogElementBinding::HTMLDialogElementBinding::DefineDOMInterface),
        (b"TestBindingPairIterable" as &'static [u8], codegen::Bindings::TestBindingPairIterableBinding::TestBindingPairIterableBinding::DefineDOMInterface),
        (b"HTMLBaseElement" as &'static [u8], codegen::Bindings::HTMLBaseElementBinding::HTMLBaseElementBinding::DefineDOMInterface),
        (b"Client" as &'static [u8], codegen::Bindings::ClientBinding::ClientBinding::DefineDOMInterface),
        (b"WebGLShaderPrecisionFormat" as &'static [u8], codegen::Bindings::WebGLShaderPrecisionFormatBinding::WebGLShaderPrecisionFormatBinding::DefineDOMInterface),
        (b"URL" as &'static [u8], codegen::Bindings::URLBinding::URLBinding::DefineDOMInterface),
        (b"WorkletGlobalScope" as &'static [u8], codegen::Bindings::WorkletGlobalScopeBinding::WorkletGlobalScopeBinding::DefineDOMInterface),
        (b"ServiceWorkerGlobalScope" as &'static [u8], codegen::Bindings::ServiceWorkerGlobalScopeBinding::ServiceWorkerGlobalScopeBinding::DefineDOMInterface),
        (b"PermissionStatus" as &'static [u8], codegen::Bindings::PermissionStatusBinding::PermissionStatusBinding::DefineDOMInterface),
        (b"HTMLButtonElement" as &'static [u8], codegen::Bindings::HTMLButtonElementBinding::HTMLButtonElementBinding::DefineDOMInterface),
        (b"PerformanceMark" as &'static [u8], codegen::Bindings::PerformanceMarkBinding::PerformanceMarkBinding::DefineDOMInterface),
        (b"Node" as &'static [u8], codegen::Bindings::NodeBinding::NodeBinding::DefineDOMInterface),
        (b"HTMLTableHeaderCellElement" as &'static [u8], codegen::Bindings::HTMLTableHeaderCellElementBinding::HTMLTableHeaderCellElementBinding::DefineDOMInterface),
        (b"DOMParser" as &'static [u8], codegen::Bindings::DOMParserBinding::DOMParserBinding::DefineDOMInterface),
        (b"HTMLPreElement" as &'static [u8], codegen::Bindings::HTMLPreElementBinding::HTMLPreElementBinding::DefineDOMInterface),
        (b"DOMPoint" as &'static [u8], codegen::Bindings::DOMPointBinding::DOMPointBinding::DefineDOMInterface),
        (b"TreeWalker" as &'static [u8], codegen::Bindings::TreeWalkerBinding::TreeWalkerBinding::DefineDOMInterface),
        (b"VRPose" as &'static [u8], codegen::Bindings::VRPoseBinding::VRPoseBinding::DefineDOMInterface),
        (b"console" as &'static [u8], codegen::Bindings::ConsoleBinding::ConsoleBinding::DefineDOMInterface),
        (b"HTMLPictureElement" as &'static [u8], codegen::Bindings::HTMLPictureElementBinding::HTMLPictureElementBinding::DefineDOMInterface),
        (b"CompositionEvent" as &'static [u8], codegen::Bindings::CompositionEventBinding::CompositionEventBinding::DefineDOMInterface),
        (b"CSSStyleDeclaration" as &'static [u8], codegen::Bindings::CSSStyleDeclarationBinding::CSSStyleDeclarationBinding::DefineDOMInterface),
        (b"WebGLContextEvent" as &'static [u8], codegen::Bindings::WebGLContextEventBinding::WebGLContextEventBinding::DefineDOMInterface),
        (b"Worklet" as &'static [u8], codegen::Bindings::WorkletBinding::WorkletBinding::DefineDOMInterface),
        (b"Element" as &'static [u8], codegen::Bindings::ElementBinding::ElementBinding::DefineDOMInterface),
        (b"Location" as &'static [u8], codegen::Bindings::LocationBinding::LocationBinding::DefineDOMInterface),
        (b"BluetoothRemoteGATTCharacteristic" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTCharacteristicBinding::BluetoothRemoteGATTCharacteristicBinding::DefineDOMInterface),
        (b"FormData" as &'static [u8], codegen::Bindings::FormDataBinding::FormDataBinding::DefineDOMInterface),
        (b"Document" as &'static [u8], codegen::Bindings::DocumentBinding::DocumentBinding::DefineDOMInterface),
        (b"Window" as &'static [u8], codegen::Bindings::WindowBinding::WindowBinding::DefineDOMInterface),
        (b"VRStageParameters" as &'static [u8], codegen::Bindings::VRStageParametersBinding::VRStageParametersBinding::DefineDOMInterface),
        (b"HTMLFrameElement" as &'static [u8], codegen::Bindings::HTMLFrameElementBinding::HTMLFrameElementBinding::DefineDOMInterface),
        (b"ServiceWorkerRegistration" as &'static [u8], codegen::Bindings::ServiceWorkerRegistrationBinding::ServiceWorkerRegistrationBinding::DefineDOMInterface),
        (b"EventTarget" as &'static [u8], codegen::Bindings::EventTargetBinding::EventTargetBinding::DefineDOMInterface),
        (b"CSSImportRule" as &'static [u8], codegen::Bindings::CSSImportRuleBinding::CSSImportRuleBinding::DefineDOMInterface),
        (b"GamepadList" as &'static [u8], codegen::Bindings::GamepadListBinding::GamepadListBinding::DefineDOMInterface),
        (b"ServiceWorker" as &'static [u8], codegen::Bindings::ServiceWorkerBinding::ServiceWorkerBinding::DefineDOMInterface),
        (b"MimeTypeArray" as &'static [u8], codegen::Bindings::MimeTypeArrayBinding::MimeTypeArrayBinding::DefineDOMInterface),
        (b"NodeIterator" as &'static [u8], codegen::Bindings::NodeIteratorBinding::NodeIteratorBinding::DefineDOMInterface),
        (b"CSSKeyframeRule" as &'static [u8], codegen::Bindings::CSSKeyframeRuleBinding::CSSKeyframeRuleBinding::DefineDOMInterface),
        (b"BluetoothCharacteristicProperties" as &'static [u8], codegen::Bindings::BluetoothCharacteristicPropertiesBinding::BluetoothCharacteristicPropertiesBinding::DefineDOMInterface),
        (b"XMLHttpRequestEventTarget" as &'static [u8], codegen::Bindings::XMLHttpRequestEventTargetBinding::XMLHttpRequestEventTargetBinding::DefineDOMInterface),
        (b"GamepadButton" as &'static [u8], codegen::Bindings::GamepadButtonBinding::GamepadButtonBinding::DefineDOMInterface),
        (b"HTMLParamElement" as &'static [u8], codegen::Bindings::HTMLParamElementBinding::HTMLParamElementBinding::DefineDOMInterface),
        (b"HTMLSelectElement" as &'static [u8], codegen::Bindings::HTMLSelectElementBinding::HTMLSelectElementBinding::DefineDOMInterface),
        (b"VREyeParameters" as &'static [u8], codegen::Bindings::VREyeParametersBinding::VREyeParametersBinding::DefineDOMInterface),
        (b"HTMLUnknownElement" as &'static [u8], codegen::Bindings::HTMLUnknownElementBinding::HTMLUnknownElementBinding::DefineDOMInterface),
        (b"HTMLFrameSetElement" as &'static [u8], codegen::Bindings::HTMLFrameSetElementBinding::HTMLFrameSetElementBinding::DefineDOMInterface),
        (b"Performance" as &'static [u8], codegen::Bindings::PerformanceBinding::PerformanceBinding::DefineDOMInterface),
        (b"CSSFontFaceRule" as &'static [u8], codegen::Bindings::CSSFontFaceRuleBinding::CSSFontFaceRuleBinding::DefineDOMInterface),
        (b"Plugin" as &'static [u8], codegen::Bindings::PluginBinding::PluginBinding::DefineDOMInterface),
        (b"DocumentType" as &'static [u8], codegen::Bindings::DocumentTypeBinding::DocumentTypeBinding::DefineDOMInterface),
        (b"DOMMatrix" as &'static [u8], codegen::Bindings::DOMMatrixBinding::DOMMatrixBinding::DefineDOMInterface),
        (b"HTMLTableDataCellElement" as &'static [u8], codegen::Bindings::HTMLTableDataCellElementBinding::HTMLTableDataCellElementBinding::DefineDOMInterface),
        (b"HTMLSourceElement" as &'static [u8], codegen::Bindings::HTMLSourceElementBinding::HTMLSourceElementBinding::DefineDOMInterface),
        (b"BluetoothUUID" as &'static [u8], codegen::Bindings::BluetoothUUIDBinding::BluetoothUUIDBinding::DefineDOMInterface),
        (b"MessageEvent" as &'static [u8], codegen::Bindings::MessageEventBinding::MessageEventBinding::DefineDOMInterface),
        (b"HTMLQuoteElement" as &'static [u8], codegen::Bindings::HTMLQuoteElementBinding::HTMLQuoteElementBinding::DefineDOMInterface),
        (b"EventSource" as &'static [u8], codegen::Bindings::EventSourceBinding::EventSourceBinding::DefineDOMInterface),
        (b"GamepadEvent" as &'static [u8], codegen::Bindings::GamepadEventBinding::GamepadEventBinding::DefineDOMInterface),
        (b"PerformanceMeasure" as &'static [u8], codegen::Bindings::PerformanceMeasureBinding::PerformanceMeasureBinding::DefineDOMInterface),
        (b"CanvasRenderingContext2D" as &'static [u8], codegen::Bindings::CanvasRenderingContext2DBinding::CanvasRenderingContext2DBinding::DefineDOMInterface),
        (b"WebGLBuffer" as &'static [u8], codegen::Bindings::WebGLBufferBinding::WebGLBufferBinding::DefineDOMInterface),
        (b"VRDisplayCapabilities" as &'static [u8], codegen::Bindings::VRDisplayCapabilitiesBinding::VRDisplayCapabilitiesBinding::DefineDOMInterface),
        (b"WorkerGlobalScope" as &'static [u8], codegen::Bindings::WorkerGlobalScopeBinding::WorkerGlobalScopeBinding::DefineDOMInterface),
        (b"HTMLTrackElement" as &'static [u8], codegen::Bindings::HTMLTrackElementBinding::HTMLTrackElementBinding::DefineDOMInterface),
        (b"HashChangeEvent" as &'static [u8], codegen::Bindings::HashChangeEventBinding::HashChangeEventBinding::DefineDOMInterface),
        (b"MediaQueryListEvent" as &'static [u8], codegen::Bindings::MediaQueryListEventBinding::MediaQueryListEventBinding::DefineDOMInterface),
        (b"Storage" as &'static [u8], codegen::Bindings::StorageBinding::StorageBinding::DefineDOMInterface),
        (b"RadioNodeList" as &'static [u8], codegen::Bindings::RadioNodeListBinding::RadioNodeListBinding::DefineDOMInterface),
        (b"HTMLImageElement" as &'static [u8], codegen::Bindings::HTMLImageElementBinding::HTMLImageElementBinding::DefineDOMInterface),
        (b"HTMLFormElement" as &'static [u8], codegen::Bindings::HTMLFormElementBinding::HTMLFormElementBinding::DefineDOMInterface),
        (b"CSSViewportRule" as &'static [u8], codegen::Bindings::CSSViewportRuleBinding::CSSViewportRuleBinding::DefineDOMInterface),
        (b"HTMLOutputElement" as &'static [u8], codegen::Bindings::HTMLOutputElementBinding::HTMLOutputElementBinding::DefineDOMInterface),
        (b"CSSRuleList" as &'static [u8], codegen::Bindings::CSSRuleListBinding::CSSRuleListBinding::DefineDOMInterface),
        (b"Response" as &'static [u8], codegen::Bindings::ResponseBinding::ResponseBinding::DefineDOMInterface),
        (b"HTMLBRElement" as &'static [u8], codegen::Bindings::HTMLBRElementBinding::HTMLBRElementBinding::DefineDOMInterface),
        (b"HTMLHeadElement" as &'static [u8], codegen::Bindings::HTMLHeadElementBinding::HTMLHeadElementBinding::DefineDOMInterface),
        (b"DOMPointReadOnly" as &'static [u8], codegen::Bindings::DOMPointReadOnlyBinding::DOMPointReadOnlyBinding::DefineDOMInterface),
        (b"StorageEvent" as &'static [u8], codegen::Bindings::StorageEventBinding::StorageEventBinding::DefineDOMInterface),
        (b"CSSNamespaceRule" as &'static [u8], codegen::Bindings::CSSNamespaceRuleBinding::CSSNamespaceRuleBinding::DefineDOMInterface),
        (b"Range" as &'static [u8], codegen::Bindings::RangeBinding::RangeBinding::DefineDOMInterface),
        (b"HTMLTableRowElement" as &'static [u8], codegen::Bindings::HTMLTableRowElementBinding::HTMLTableRowElementBinding::DefineDOMInterface),
        (b"CSSRule" as &'static [u8], codegen::Bindings::CSSRuleBinding::CSSRuleBinding::DefineDOMInterface),
        (b"Comment" as &'static [u8], codegen::Bindings::CommentBinding::CommentBinding::DefineDOMInterface),
        (b"CSSStyleRule" as &'static [u8], codegen::Bindings::CSSStyleRuleBinding::CSSStyleRuleBinding::DefineDOMInterface),
        (b"HTMLTableColElement" as &'static [u8], codegen::Bindings::HTMLTableColElementBinding::HTMLTableColElementBinding::DefineDOMInterface),
        (b"Worker" as &'static [u8], codegen::Bindings::WorkerBinding::WorkerBinding::DefineDOMInterface),
        (b"BeforeUnloadEvent" as &'static [u8], codegen::Bindings::BeforeUnloadEventBinding::BeforeUnloadEventBinding::DefineDOMInterface),
        (b"Gamepad" as &'static [u8], codegen::Bindings::GamepadBinding::GamepadBinding::DefineDOMInterface),
        (b"HTMLProgressElement" as &'static [u8], codegen::Bindings::HTMLProgressElementBinding::HTMLProgressElementBinding::DefineDOMInterface),
        (b"XMLHttpRequest" as &'static [u8], codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestBinding::DefineDOMInterface),
        (b"WebGLUniformLocation" as &'static [u8], codegen::Bindings::WebGLUniformLocationBinding::WebGLUniformLocationBinding::DefineDOMInterface),
        (b"InputEvent" as &'static [u8], codegen::Bindings::InputEventBinding::InputEventBinding::DefineDOMInterface),
        (b"CanvasGradient" as &'static [u8], codegen::Bindings::CanvasGradientBinding::CanvasGradientBinding::DefineDOMInterface),
        (b"ImageData" as &'static [u8], codegen::Bindings::ImageDataBinding::ImageDataBinding::DefineDOMInterface),
        (b"HTMLLegendElement" as &'static [u8], codegen::Bindings::HTMLLegendElementBinding::HTMLLegendElementBinding::DefineDOMInterface),
        (b"Text" as &'static [u8], codegen::Bindings::TextBinding::TextBinding::DefineDOMInterface),
        (b"HTMLStyleElement" as &'static [u8], codegen::Bindings::HTMLStyleElementBinding::HTMLStyleElementBinding::DefineDOMInterface),
        (b"PerformanceEntry" as &'static [u8], codegen::Bindings::PerformanceEntryBinding::PerformanceEntryBinding::DefineDOMInterface),
        (b"BluetoothRemoteGATTDescriptor" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTDescriptorBinding::BluetoothRemoteGATTDescriptorBinding::DefineDOMInterface),
        (b"DOMException" as &'static [u8], codegen::Bindings::DOMExceptionBinding::DOMExceptionBinding::DefineDOMInterface),
        (b"BluetoothPermissionResult" as &'static [u8], codegen::Bindings::BluetoothPermissionResultBinding::BluetoothPermissionResultBinding::DefineDOMInterface),
        (b"CSSStyleValue" as &'static [u8], codegen::Bindings::CSSStyleValueBinding::CSSStyleValueBinding::DefineDOMInterface),
        (b"DedicatedWorkerGlobalScope" as &'static [u8], codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::DefineDOMInterface),
        (b"UIEvent" as &'static [u8], codegen::Bindings::UIEventBinding::UIEventBinding::DefineDOMInterface),
        (b"HTMLTableCellElement" as &'static [u8], codegen::Bindings::HTMLTableCellElementBinding::HTMLTableCellElementBinding::DefineDOMInterface),
        (b"WebGLActiveInfo" as &'static [u8], codegen::Bindings::WebGLActiveInfoBinding::WebGLActiveInfoBinding::DefineDOMInterface),
        (b"StyleSheet" as &'static [u8], codegen::Bindings::StyleSheetBinding::StyleSheetBinding::DefineDOMInterface),
        (b"TestBinding" as &'static [u8], codegen::Bindings::TestBindingBinding::TestBindingBinding::DefineDOMInterface),
        (b"WorkerLocation" as &'static [u8], codegen::Bindings::WorkerLocationBinding::WorkerLocationBinding::DefineDOMInterface),
        (b"DOMRect" as &'static [u8], codegen::Bindings::DOMRectBinding::DOMRectBinding::DefineDOMInterface),
        (b"HTMLParagraphElement" as &'static [u8], codegen::Bindings::HTMLParagraphElementBinding::HTMLParagraphElementBinding::DefineDOMInterface),
        (b"ProgressEvent" as &'static [u8], codegen::Bindings::ProgressEventBinding::ProgressEventBinding::DefineDOMInterface),
        (b"BluetoothRemoteGATTService" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTServiceBinding::BluetoothRemoteGATTServiceBinding::DefineDOMInterface),
        (b"DOMImplementation" as &'static [u8], codegen::Bindings::DOMImplementationBinding::DOMImplementationBinding::DefineDOMInterface),
        (b"SVGSVGElement" as &'static [u8], codegen::Bindings::SVGSVGElementBinding::SVGSVGElementBinding::DefineDOMInterface),
        (b"WebGLFramebuffer" as &'static [u8], codegen::Bindings::WebGLFramebufferBinding::WebGLFramebufferBinding::DefineDOMInterface),
        (b"HTMLTableElement" as &'static [u8], codegen::Bindings::HTMLTableElementBinding::HTMLTableElementBinding::DefineDOMInterface),
        (b"VRDisplayEvent" as &'static [u8], codegen::Bindings::VRDisplayEventBinding::VRDisplayEventBinding::DefineDOMInterface),
        (b"HTMLTemplateElement" as &'static [u8], codegen::Bindings::HTMLTemplateElementBinding::HTMLTemplateElementBinding::DefineDOMInterface),
        (b"TextDecoder" as &'static [u8], codegen::Bindings::TextDecoderBinding::TextDecoderBinding::DefineDOMInterface),
        (b"Blob" as &'static [u8], codegen::Bindings::BlobBinding::BlobBinding::DefineDOMInterface),
        (b"HTMLElement" as &'static [u8], codegen::Bindings::HTMLElementBinding::HTMLElementBinding::DefineDOMInterface),
        (b"CSSGroupingRule" as &'static [u8], codegen::Bindings::CSSGroupingRuleBinding::CSSGroupingRuleBinding::DefineDOMInterface),
        (b"HTMLMeterElement" as &'static [u8], codegen::Bindings::HTMLMeterElementBinding::HTMLMeterElementBinding::DefineDOMInterface),
        (b"HTMLDListElement" as &'static [u8], codegen::Bindings::HTMLDListElementBinding::HTMLDListElementBinding::DefineDOMInterface),
        (b"DOMRectReadOnly" as &'static [u8], codegen::Bindings::DOMRectReadOnlyBinding::DOMRectReadOnlyBinding::DefineDOMInterface),
        (b"TestBindingProxy" as &'static [u8], codegen::Bindings::TestBindingProxyBinding::TestBindingProxyBinding::DefineDOMInterface),
        (b"FileReaderSync" as &'static [u8], codegen::Bindings::FileReaderSyncBinding::FileReaderSyncBinding::DefineDOMInterface),
        (b"TestWorklet" as &'static [u8], codegen::Bindings::TestWorkletBinding::TestWorkletBinding::DefineDOMInterface),
        (b"NodeFilter" as &'static [u8], codegen::Bindings::NodeFilterBinding::NodeFilterBinding::DefineDOMInterface),
        (b"PageTransitionEvent" as &'static [u8], codegen::Bindings::PageTransitionEventBinding::PageTransitionEventBinding::DefineDOMInterface),
        (b"FocusEvent" as &'static [u8], codegen::Bindings::FocusEventBinding::FocusEventBinding::DefineDOMInterface),
        (b"Navigator" as &'static [u8], codegen::Bindings::NavigatorBinding::NavigatorBinding::DefineDOMInterface),
        (b"HTMLLinkElement" as &'static [u8], codegen::Bindings::HTMLLinkElementBinding::HTMLLinkElementBinding::DefineDOMInterface),
        (b"DOMStringMap" as &'static [u8], codegen::Bindings::DOMStringMapBinding::DOMStringMapBinding::DefineDOMInterface),
        (b"Event" as &'static [u8], codegen::Bindings::EventBinding::EventBinding::DefineDOMInterface),
        (b"URLSearchParams" as &'static [u8], codegen::Bindings::URLSearchParamsBinding::URLSearchParamsBinding::DefineDOMInterface),
        (b"ExtendableMessageEvent" as &'static [u8], codegen::Bindings::ExtendableMessageEventBinding::ExtendableMessageEventBinding::DefineDOMInterface),
        (b"HTMLMetaElement" as &'static [u8], codegen::Bindings::HTMLMetaElementBinding::HTMLMetaElementBinding::DefineDOMInterface),
        (b"Image" as &'static [u8], codegen::Bindings::HTMLImageElementBinding::HTMLImageElementBinding::DefineDOMInterface),
        (b"TransitionEvent" as &'static [u8], codegen::Bindings::TransitionEventBinding::TransitionEventBinding::DefineDOMInterface),
        (b"HTMLTimeElement" as &'static [u8], codegen::Bindings::HTMLTimeElementBinding::HTMLTimeElementBinding::DefineDOMInterface),
        (b"VRFrameData" as &'static [u8], codegen::Bindings::VRFrameDataBinding::VRFrameDataBinding::DefineDOMInterface),
        (b"HTMLHRElement" as &'static [u8], codegen::Bindings::HTMLHRElementBinding::HTMLHRElementBinding::DefineDOMInterface),
        (b"HTMLOptionsCollection" as &'static [u8], codegen::Bindings::HTMLOptionsCollectionBinding::HTMLOptionsCollectionBinding::DefineDOMInterface),
        (b"PaintRenderingContext2D" as &'static [u8], codegen::Bindings::PaintRenderingContext2DBinding::PaintRenderingContext2DBinding::DefineDOMInterface),
        (b"ValidityState" as &'static [u8], codegen::Bindings::ValidityStateBinding::ValidityStateBinding::DefineDOMInterface),
        (b"History" as &'static [u8], codegen::Bindings::HistoryBinding::HistoryBinding::DefineDOMInterface),
        (b"HTMLFontElement" as &'static [u8], codegen::Bindings::HTMLFontElementBinding::HTMLFontElementBinding::DefineDOMInterface),
        (b"HTMLOListElement" as &'static [u8], codegen::Bindings::HTMLOListElementBinding::HTMLOListElementBinding::DefineDOMInterface),
        (b"HTMLOptGroupElement" as &'static [u8], codegen::Bindings::HTMLOptGroupElementBinding::HTMLOptGroupElementBinding::DefineDOMInterface),
        (b"StylePropertyMapReadOnly" as &'static [u8], codegen::Bindings::StylePropertyMapReadOnlyBinding::StylePropertyMapReadOnlyBinding::DefineDOMInterface),
        (b"WorkerNavigator" as &'static [u8], codegen::Bindings::WorkerNavigatorBinding::WorkerNavigatorBinding::DefineDOMInterface),
        (b"XMLDocument" as &'static [u8], codegen::Bindings::XMLDocumentBinding::XMLDocumentBinding::DefineDOMInterface),
    ]),
};
