pub unsafe fn init_MAP<TH: TypeHolderTrait>() {
    MAP.entries = ::phf::Slice::Static(&[
        (b"CharacterData" as &'static [u8], codegen::Bindings::CharacterDataBinding::CharacterDataBinding::DefineDOMInterface::<TH>),
        (b"HTMLAudioElement" as &'static [u8], codegen::Bindings::HTMLAudioElementBinding::HTMLAudioElementBinding::DefineDOMInterface::<TH>),
        (b"CloseEvent" as &'static [u8], codegen::Bindings::CloseEventBinding::CloseEventBinding::DefineDOMInterface::<TH>),
        (b"BluetoothDevice" as &'static [u8], codegen::Bindings::BluetoothDeviceBinding::BluetoothDeviceBinding::DefineDOMInterface::<TH>),
        (b"BluetoothAdvertisingEvent" as &'static [u8], codegen::Bindings::BluetoothAdvertisingEventBinding::BluetoothAdvertisingEventBinding::DefineDOMInterface::<TH>),
        (b"Permissions" as &'static [u8], codegen::Bindings::PermissionsBinding::PermissionsBinding::DefineDOMInterface::<TH>),
        (b"HTMLHeadingElement" as &'static [u8], codegen::Bindings::HTMLHeadingElementBinding::HTMLHeadingElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLEmbedElement" as &'static [u8], codegen::Bindings::HTMLEmbedElementBinding::HTMLEmbedElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLObjectElement" as &'static [u8], codegen::Bindings::HTMLObjectElementBinding::HTMLObjectElementBinding::DefineDOMInterface::<TH>),
        (b"ErrorEvent" as &'static [u8], codegen::Bindings::ErrorEventBinding::ErrorEventBinding::DefineDOMInterface::<TH>),
        (b"MediaQueryList" as &'static [u8], codegen::Bindings::MediaQueryListBinding::MediaQueryListBinding::DefineDOMInterface::<TH>),
        (b"WebGLRenderbuffer" as &'static [u8], codegen::Bindings::WebGLRenderbufferBinding::WebGLRenderbufferBinding::DefineDOMInterface::<TH>),
        (b"MediaList" as &'static [u8], codegen::Bindings::MediaListBinding::MediaListBinding::DefineDOMInterface::<TH>),
        (b"FileReader" as &'static [u8], codegen::Bindings::FileReaderBinding::FileReaderBinding::DefineDOMInterface::<TH>),
        (b"HTMLDivElement" as &'static [u8], codegen::Bindings::HTMLDivElementBinding::HTMLDivElementBinding::DefineDOMInterface::<TH>),
        (b"Crypto" as &'static [u8], codegen::Bindings::CryptoBinding::CryptoBinding::DefineDOMInterface::<TH>),
        (b"Screen" as &'static [u8], codegen::Bindings::ScreenBinding::ScreenBinding::DefineDOMInterface::<TH>),
        (b"HTMLAreaElement" as &'static [u8], codegen::Bindings::HTMLAreaElementBinding::HTMLAreaElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLCollection" as &'static [u8], codegen::Bindings::HTMLCollectionBinding::HTMLCollectionBinding::DefineDOMInterface::<TH>),
        (b"ExtendableEvent" as &'static [u8], codegen::Bindings::ExtendableEventBinding::ExtendableEventBinding::DefineDOMInterface::<TH>),
        (b"PerformanceObserverEntryList" as &'static [u8], codegen::Bindings::PerformanceObserverEntryListBinding::PerformanceObserverEntryListBinding::DefineDOMInterface::<TH>),
        (b"HTMLAnchorElement" as &'static [u8], codegen::Bindings::HTMLAnchorElementBinding::HTMLAnchorElementBinding::DefineDOMInterface::<TH>),
        (b"Headers" as &'static [u8], codegen::Bindings::HeadersBinding::HeadersBinding::DefineDOMInterface::<TH>),
        (b"WebGL2RenderingContext" as &'static [u8], codegen::Bindings::WebGL2RenderingContextBinding::WebGL2RenderingContextBinding::DefineDOMInterface::<TH>),
        (b"NodeList" as &'static [u8], codegen::Bindings::NodeListBinding::NodeListBinding::DefineDOMInterface::<TH>),
        (b"Touch" as &'static [u8], codegen::Bindings::TouchBinding::TouchBinding::DefineDOMInterface::<TH>),
        (b"HTMLMediaElement" as &'static [u8], codegen::Bindings::HTMLMediaElementBinding::HTMLMediaElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLInputElement" as &'static [u8], codegen::Bindings::HTMLInputElementBinding::HTMLInputElementBinding::DefineDOMInterface::<TH>),
        (b"DocumentFragment" as &'static [u8], codegen::Bindings::DocumentFragmentBinding::DocumentFragmentBinding::DefineDOMInterface::<TH>),
        (b"Bluetooth" as &'static [u8], codegen::Bindings::BluetoothBinding::BluetoothBinding::DefineDOMInterface::<TH>),
        (b"XMLHttpRequestUpload" as &'static [u8], codegen::Bindings::XMLHttpRequestUploadBinding::XMLHttpRequestUploadBinding::DefineDOMInterface::<TH>),
        (b"DOMTokenList" as &'static [u8], codegen::Bindings::DOMTokenListBinding::DOMTokenListBinding::DefineDOMInterface::<TH>),
        (b"ServiceWorkerContainer" as &'static [u8], codegen::Bindings::ServiceWorkerContainerBinding::ServiceWorkerContainerBinding::DefineDOMInterface::<TH>),
        (b"CSSConditionRule" as &'static [u8], codegen::Bindings::CSSConditionRuleBinding::CSSConditionRuleBinding::DefineDOMInterface::<TH>),
        (b"SVGGraphicsElement" as &'static [u8], codegen::Bindings::SVGGraphicsElementBinding::SVGGraphicsElementBinding::DefineDOMInterface::<TH>),
        (b"PerformancePaintTiming" as &'static [u8], codegen::Bindings::PerformancePaintTimingBinding::PerformancePaintTimingBinding::DefineDOMInterface::<TH>),
        (b"HTMLFormControlsCollection" as &'static [u8], codegen::Bindings::HTMLFormControlsCollectionBinding::HTMLFormControlsCollectionBinding::DefineDOMInterface::<TH>),
        (b"HTMLLIElement" as &'static [u8], codegen::Bindings::HTMLLIElementBinding::HTMLLIElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLVideoElement" as &'static [u8], codegen::Bindings::HTMLVideoElementBinding::HTMLVideoElementBinding::DefineDOMInterface::<TH>),
        (b"DOMQuad" as &'static [u8], codegen::Bindings::DOMQuadBinding::DOMQuadBinding::DefineDOMInterface::<TH>),
        (b"VRFieldOfView" as &'static [u8], codegen::Bindings::VRFieldOfViewBinding::VRFieldOfViewBinding::DefineDOMInterface::<TH>),
        (b"HTMLSpanElement" as &'static [u8], codegen::Bindings::HTMLSpanElementBinding::HTMLSpanElementBinding::DefineDOMInterface::<TH>),
        (b"VRDisplay" as &'static [u8], codegen::Bindings::VRDisplayBinding::VRDisplayBinding::DefineDOMInterface::<TH>),
        (b"CSS" as &'static [u8], codegen::Bindings::CSSBinding::CSSBinding::DefineDOMInterface::<TH>),
        (b"CSSMediaRule" as &'static [u8], codegen::Bindings::CSSMediaRuleBinding::CSSMediaRuleBinding::DefineDOMInterface::<TH>),
        (b"CustomElementRegistry" as &'static [u8], codegen::Bindings::CustomElementRegistryBinding::CustomElementRegistryBinding::DefineDOMInterface::<TH>),
        (b"TestRunner" as &'static [u8], codegen::Bindings::TestRunnerBinding::TestRunnerBinding::DefineDOMInterface::<TH>),
        (b"CanvasPattern" as &'static [u8], codegen::Bindings::CanvasPatternBinding::CanvasPatternBinding::DefineDOMInterface::<TH>),
        (b"WebSocket" as &'static [u8], codegen::Bindings::WebSocketBinding::WebSocketBinding::DefineDOMInterface::<TH>),
        (b"HTMLUListElement" as &'static [u8], codegen::Bindings::HTMLUListElementBinding::HTMLUListElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLBodyElement" as &'static [u8], codegen::Bindings::HTMLBodyElementBinding::HTMLBodyElementBinding::DefineDOMInterface::<TH>),
        (b"PluginArray" as &'static [u8], codegen::Bindings::PluginArrayBinding::PluginArrayBinding::DefineDOMInterface::<TH>),
        (b"File" as &'static [u8], codegen::Bindings::FileBinding::FileBinding::DefineDOMInterface::<TH>),
        (b"CSSStyleSheet" as &'static [u8], codegen::Bindings::CSSStyleSheetBinding::CSSStyleSheetBinding::DefineDOMInterface::<TH>),
        (b"TestBindingIterable" as &'static [u8], codegen::Bindings::TestBindingIterableBinding::TestBindingIterableBinding::DefineDOMInterface::<TH>),
        (b"HTMLIFrameElement" as &'static [u8], codegen::Bindings::HTMLIFrameElementBinding::HTMLIFrameElementBinding::DefineDOMInterface::<TH>),
        (b"GamepadButtonList" as &'static [u8], codegen::Bindings::GamepadButtonListBinding::GamepadButtonListBinding::DefineDOMInterface::<TH>),
        (b"TestWorkletGlobalScope" as &'static [u8], codegen::Bindings::TestWorkletGlobalScopeBinding::TestWorkletGlobalScopeBinding::DefineDOMInterface::<TH>),
        (b"CSSKeyframesRule" as &'static [u8], codegen::Bindings::CSSKeyframesRuleBinding::CSSKeyframesRuleBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableSectionElement" as &'static [u8], codegen::Bindings::HTMLTableSectionElementBinding::HTMLTableSectionElementBinding::DefineDOMInterface::<TH>),
        (b"PerformanceObserver" as &'static [u8], codegen::Bindings::PerformanceObserverBinding::PerformanceObserverBinding::DefineDOMInterface::<TH>),
        (b"WebGLShader" as &'static [u8], codegen::Bindings::WebGLShaderBinding::WebGLShaderBinding::DefineDOMInterface::<TH>),
        (b"HTMLDetailsElement" as &'static [u8], codegen::Bindings::HTMLDetailsElementBinding::HTMLDetailsElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLCanvasElement" as &'static [u8], codegen::Bindings::HTMLCanvasElementBinding::HTMLCanvasElementBinding::DefineDOMInterface::<TH>),
        (b"WebGLRenderingContext" as &'static [u8], codegen::Bindings::WebGLRenderingContextBinding::WebGLRenderingContextBinding::DefineDOMInterface::<TH>),
        (b"HTMLLabelElement" as &'static [u8], codegen::Bindings::HTMLLabelElementBinding::HTMLLabelElementBinding::DefineDOMInterface::<TH>),
        (b"CSSSupportsRule" as &'static [u8], codegen::Bindings::CSSSupportsRuleBinding::CSSSupportsRuleBinding::DefineDOMInterface::<TH>),
        (b"PaintWorkletGlobalScope" as &'static [u8], codegen::Bindings::PaintWorkletGlobalScopeBinding::PaintWorkletGlobalScopeBinding::DefineDOMInterface::<TH>),
        (b"MouseEvent" as &'static [u8], codegen::Bindings::MouseEventBinding::MouseEventBinding::DefineDOMInterface::<TH>),
        (b"TouchList" as &'static [u8], codegen::Bindings::TouchListBinding::TouchListBinding::DefineDOMInterface::<TH>),
        (b"MutationRecord" as &'static [u8], codegen::Bindings::MutationRecordBinding::MutationRecordBinding::DefineDOMInterface::<TH>),
        (b"KeyboardEvent" as &'static [u8], codegen::Bindings::KeyboardEventBinding::KeyboardEventBinding::DefineDOMInterface::<TH>),
        (b"MimeType" as &'static [u8], codegen::Bindings::MimeTypeBinding::MimeTypeBinding::DefineDOMInterface::<TH>),
        (b"BluetoothRemoteGATTServer" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTServerBinding::BluetoothRemoteGATTServerBinding::DefineDOMInterface::<TH>),
        (b"PerformanceTiming" as &'static [u8], codegen::Bindings::PerformanceTimingBinding::PerformanceTimingBinding::DefineDOMInterface::<TH>),
        (b"HTMLOptionElement" as &'static [u8], codegen::Bindings::HTMLOptionElementBinding::HTMLOptionElementBinding::DefineDOMInterface::<TH>),
        (b"MediaError" as &'static [u8], codegen::Bindings::MediaErrorBinding::MediaErrorBinding::DefineDOMInterface::<TH>),
        (b"HTMLDirectoryElement" as &'static [u8], codegen::Bindings::HTMLDirectoryElementBinding::HTMLDirectoryElementBinding::DefineDOMInterface::<TH>),
        (b"WebGLProgram" as &'static [u8], codegen::Bindings::WebGLProgramBinding::WebGLProgramBinding::DefineDOMInterface::<TH>),
        (b"FileList" as &'static [u8], codegen::Bindings::FileListBinding::FileListBinding::DefineDOMInterface::<TH>),
        (b"HTMLDataListElement" as &'static [u8], codegen::Bindings::HTMLDataListElementBinding::HTMLDataListElementBinding::DefineDOMInterface::<TH>),
        (b"StyleSheetList" as &'static [u8], codegen::Bindings::StyleSheetListBinding::StyleSheetListBinding::DefineDOMInterface::<TH>),
        (b"CustomEvent" as &'static [u8], codegen::Bindings::CustomEventBinding::CustomEventBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableCaptionElement" as &'static [u8], codegen::Bindings::HTMLTableCaptionElementBinding::HTMLTableCaptionElementBinding::DefineDOMInterface::<TH>),
        (b"DOMMatrixReadOnly" as &'static [u8], codegen::Bindings::DOMMatrixReadOnlyBinding::DOMMatrixReadOnlyBinding::DefineDOMInterface::<TH>),
        (b"PaintSize" as &'static [u8], codegen::Bindings::PaintSizeBinding::PaintSizeBinding::DefineDOMInterface::<TH>),
        (b"Attr" as &'static [u8], codegen::Bindings::AttrBinding::AttrBinding::DefineDOMInterface::<TH>),
        (b"MutationObserver" as &'static [u8], codegen::Bindings::MutationObserverBinding::MutationObserverBinding::DefineDOMInterface::<TH>),
        (b"WebGLObject" as &'static [u8], codegen::Bindings::WebGLObjectBinding::WebGLObjectBinding::DefineDOMInterface::<TH>),
        (b"SVGElement" as &'static [u8], codegen::Bindings::SVGElementBinding::SVGElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLTitleElement" as &'static [u8], codegen::Bindings::HTMLTitleElementBinding::HTMLTitleElementBinding::DefineDOMInterface::<TH>),
        (b"PopStateEvent" as &'static [u8], codegen::Bindings::PopStateEventBinding::PopStateEventBinding::DefineDOMInterface::<TH>),
        (b"ProcessingInstruction" as &'static [u8], codegen::Bindings::ProcessingInstructionBinding::ProcessingInstructionBinding::DefineDOMInterface::<TH>),
        (b"HTMLTextAreaElement" as &'static [u8], codegen::Bindings::HTMLTextAreaElementBinding::HTMLTextAreaElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLScriptElement" as &'static [u8], codegen::Bindings::HTMLScriptElementBinding::HTMLScriptElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLModElement" as &'static [u8], codegen::Bindings::HTMLModElementBinding::HTMLModElementBinding::DefineDOMInterface::<TH>),
        (b"Request" as &'static [u8], codegen::Bindings::RequestBinding::RequestBinding::DefineDOMInterface::<TH>),
        (b"HTMLHtmlElement" as &'static [u8], codegen::Bindings::HTMLHtmlElementBinding::HTMLHtmlElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLDataElement" as &'static [u8], codegen::Bindings::HTMLDataElementBinding::HTMLDataElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLFieldSetElement" as &'static [u8], codegen::Bindings::HTMLFieldSetElementBinding::HTMLFieldSetElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLMapElement" as &'static [u8], codegen::Bindings::HTMLMapElementBinding::HTMLMapElementBinding::DefineDOMInterface::<TH>),
        (b"NamedNodeMap" as &'static [u8], codegen::Bindings::NamedNodeMapBinding::NamedNodeMapBinding::DefineDOMInterface::<TH>),
        (b"TextEncoder" as &'static [u8], codegen::Bindings::TextEncoderBinding::TextEncoderBinding::DefineDOMInterface::<TH>),
        (b"TouchEvent" as &'static [u8], codegen::Bindings::TouchEventBinding::TouchEventBinding::DefineDOMInterface::<TH>),
        (b"WebGLTexture" as &'static [u8], codegen::Bindings::WebGLTextureBinding::WebGLTextureBinding::DefineDOMInterface::<TH>),
        (b"HTMLDialogElement" as &'static [u8], codegen::Bindings::HTMLDialogElementBinding::HTMLDialogElementBinding::DefineDOMInterface::<TH>),
        (b"TestBindingPairIterable" as &'static [u8], codegen::Bindings::TestBindingPairIterableBinding::TestBindingPairIterableBinding::DefineDOMInterface::<TH>),
        (b"HTMLBaseElement" as &'static [u8], codegen::Bindings::HTMLBaseElementBinding::HTMLBaseElementBinding::DefineDOMInterface::<TH>),
        (b"Client" as &'static [u8], codegen::Bindings::ClientBinding::ClientBinding::DefineDOMInterface::<TH>),
        (b"WebGLShaderPrecisionFormat" as &'static [u8], codegen::Bindings::WebGLShaderPrecisionFormatBinding::WebGLShaderPrecisionFormatBinding::DefineDOMInterface::<TH>),
        (b"URL" as &'static [u8], codegen::Bindings::URLBinding::URLBinding::DefineDOMInterface::<TH>),
        (b"WorkletGlobalScope" as &'static [u8], codegen::Bindings::WorkletGlobalScopeBinding::WorkletGlobalScopeBinding::DefineDOMInterface::<TH>),
        (b"ServiceWorkerGlobalScope" as &'static [u8], codegen::Bindings::ServiceWorkerGlobalScopeBinding::ServiceWorkerGlobalScopeBinding::DefineDOMInterface::<TH>),
        (b"PermissionStatus" as &'static [u8], codegen::Bindings::PermissionStatusBinding::PermissionStatusBinding::DefineDOMInterface::<TH>),
        (b"HTMLButtonElement" as &'static [u8], codegen::Bindings::HTMLButtonElementBinding::HTMLButtonElementBinding::DefineDOMInterface::<TH>),
        (b"PerformanceMark" as &'static [u8], codegen::Bindings::PerformanceMarkBinding::PerformanceMarkBinding::DefineDOMInterface::<TH>),
        (b"Node" as &'static [u8], codegen::Bindings::NodeBinding::NodeBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableHeaderCellElement" as &'static [u8], codegen::Bindings::HTMLTableHeaderCellElementBinding::HTMLTableHeaderCellElementBinding::DefineDOMInterface::<TH>),
        (b"DOMParser" as &'static [u8], codegen::Bindings::DOMParserBinding::DOMParserBinding::DefineDOMInterface::<TH>),
        (b"HTMLPreElement" as &'static [u8], codegen::Bindings::HTMLPreElementBinding::HTMLPreElementBinding::DefineDOMInterface::<TH>),
        (b"DOMPoint" as &'static [u8], codegen::Bindings::DOMPointBinding::DOMPointBinding::DefineDOMInterface::<TH>),
        (b"TreeWalker" as &'static [u8], codegen::Bindings::TreeWalkerBinding::TreeWalkerBinding::DefineDOMInterface::<TH>),
        (b"VRPose" as &'static [u8], codegen::Bindings::VRPoseBinding::VRPoseBinding::DefineDOMInterface::<TH>),
        (b"console" as &'static [u8], codegen::Bindings::ConsoleBinding::ConsoleBinding::DefineDOMInterface),
        (b"HTMLPictureElement" as &'static [u8], codegen::Bindings::HTMLPictureElementBinding::HTMLPictureElementBinding::DefineDOMInterface::<TH>),
        (b"CompositionEvent" as &'static [u8], codegen::Bindings::CompositionEventBinding::CompositionEventBinding::DefineDOMInterface::<TH>),
        (b"CSSStyleDeclaration" as &'static [u8], codegen::Bindings::CSSStyleDeclarationBinding::CSSStyleDeclarationBinding::DefineDOMInterface::<TH>),
        (b"WebGLContextEvent" as &'static [u8], codegen::Bindings::WebGLContextEventBinding::WebGLContextEventBinding::DefineDOMInterface::<TH>),
        (b"Worklet" as &'static [u8], codegen::Bindings::WorkletBinding::WorkletBinding::DefineDOMInterface::<TH>),
        (b"Element" as &'static [u8], codegen::Bindings::ElementBinding::ElementBinding::DefineDOMInterface::<TH>),
        (b"Location" as &'static [u8], codegen::Bindings::LocationBinding::LocationBinding::DefineDOMInterface::<TH>),
        (b"BluetoothRemoteGATTCharacteristic" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTCharacteristicBinding::BluetoothRemoteGATTCharacteristicBinding::DefineDOMInterface::<TH>),
        (b"FormData" as &'static [u8], codegen::Bindings::FormDataBinding::FormDataBinding::DefineDOMInterface::<TH>),
        (b"Document" as &'static [u8], codegen::Bindings::DocumentBinding::DocumentBinding::DefineDOMInterface::<TH>),
        (b"Window" as &'static [u8], codegen::Bindings::WindowBinding::WindowBinding::DefineDOMInterface::<TH>),
        (b"VRStageParameters" as &'static [u8], codegen::Bindings::VRStageParametersBinding::VRStageParametersBinding::DefineDOMInterface::<TH>),
        (b"HTMLFrameElement" as &'static [u8], codegen::Bindings::HTMLFrameElementBinding::HTMLFrameElementBinding::DefineDOMInterface::<TH>),
        (b"ServiceWorkerRegistration" as &'static [u8], codegen::Bindings::ServiceWorkerRegistrationBinding::ServiceWorkerRegistrationBinding::DefineDOMInterface::<TH>),
        (b"EventTarget" as &'static [u8], codegen::Bindings::EventTargetBinding::EventTargetBinding::DefineDOMInterface::<TH>),
        (b"CSSImportRule" as &'static [u8], codegen::Bindings::CSSImportRuleBinding::CSSImportRuleBinding::DefineDOMInterface::<TH>),
        (b"GamepadList" as &'static [u8], codegen::Bindings::GamepadListBinding::GamepadListBinding::DefineDOMInterface::<TH>),
        (b"ServiceWorker" as &'static [u8], codegen::Bindings::ServiceWorkerBinding::ServiceWorkerBinding::DefineDOMInterface::<TH>),
        (b"MimeTypeArray" as &'static [u8], codegen::Bindings::MimeTypeArrayBinding::MimeTypeArrayBinding::DefineDOMInterface::<TH>),
        (b"NodeIterator" as &'static [u8], codegen::Bindings::NodeIteratorBinding::NodeIteratorBinding::DefineDOMInterface::<TH>),
        (b"CSSKeyframeRule" as &'static [u8], codegen::Bindings::CSSKeyframeRuleBinding::CSSKeyframeRuleBinding::DefineDOMInterface::<TH>),
        (b"BluetoothCharacteristicProperties" as &'static [u8], codegen::Bindings::BluetoothCharacteristicPropertiesBinding::BluetoothCharacteristicPropertiesBinding::DefineDOMInterface::<TH>),
        (b"XMLHttpRequestEventTarget" as &'static [u8], codegen::Bindings::XMLHttpRequestEventTargetBinding::XMLHttpRequestEventTargetBinding::DefineDOMInterface::<TH>),
        (b"GamepadButton" as &'static [u8], codegen::Bindings::GamepadButtonBinding::GamepadButtonBinding::DefineDOMInterface::<TH>),
        (b"HTMLParamElement" as &'static [u8], codegen::Bindings::HTMLParamElementBinding::HTMLParamElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLSelectElement" as &'static [u8], codegen::Bindings::HTMLSelectElementBinding::HTMLSelectElementBinding::DefineDOMInterface::<TH>),
        (b"VREyeParameters" as &'static [u8], codegen::Bindings::VREyeParametersBinding::VREyeParametersBinding::DefineDOMInterface::<TH>),
        (b"HTMLUnknownElement" as &'static [u8], codegen::Bindings::HTMLUnknownElementBinding::HTMLUnknownElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLFrameSetElement" as &'static [u8], codegen::Bindings::HTMLFrameSetElementBinding::HTMLFrameSetElementBinding::DefineDOMInterface::<TH>),
        (b"Performance" as &'static [u8], codegen::Bindings::PerformanceBinding::PerformanceBinding::DefineDOMInterface::<TH>),
        (b"CSSFontFaceRule" as &'static [u8], codegen::Bindings::CSSFontFaceRuleBinding::CSSFontFaceRuleBinding::DefineDOMInterface::<TH>),
        (b"Plugin" as &'static [u8], codegen::Bindings::PluginBinding::PluginBinding::DefineDOMInterface::<TH>),
        (b"DocumentType" as &'static [u8], codegen::Bindings::DocumentTypeBinding::DocumentTypeBinding::DefineDOMInterface::<TH>),
        (b"DOMMatrix" as &'static [u8], codegen::Bindings::DOMMatrixBinding::DOMMatrixBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableDataCellElement" as &'static [u8], codegen::Bindings::HTMLTableDataCellElementBinding::HTMLTableDataCellElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLSourceElement" as &'static [u8], codegen::Bindings::HTMLSourceElementBinding::HTMLSourceElementBinding::DefineDOMInterface::<TH>),
        (b"BluetoothUUID" as &'static [u8], codegen::Bindings::BluetoothUUIDBinding::BluetoothUUIDBinding::DefineDOMInterface::<TH>),
        (b"MessageEvent" as &'static [u8], codegen::Bindings::MessageEventBinding::MessageEventBinding::DefineDOMInterface::<TH>),
        (b"HTMLQuoteElement" as &'static [u8], codegen::Bindings::HTMLQuoteElementBinding::HTMLQuoteElementBinding::DefineDOMInterface::<TH>),
        (b"EventSource" as &'static [u8], codegen::Bindings::EventSourceBinding::EventSourceBinding::DefineDOMInterface::<TH>),
        (b"GamepadEvent" as &'static [u8], codegen::Bindings::GamepadEventBinding::GamepadEventBinding::DefineDOMInterface::<TH>),
        (b"PerformanceMeasure" as &'static [u8], codegen::Bindings::PerformanceMeasureBinding::PerformanceMeasureBinding::DefineDOMInterface::<TH>),
        (b"CanvasRenderingContext2D" as &'static [u8], codegen::Bindings::CanvasRenderingContext2DBinding::CanvasRenderingContext2DBinding::DefineDOMInterface::<TH>),
        (b"WebGLBuffer" as &'static [u8], codegen::Bindings::WebGLBufferBinding::WebGLBufferBinding::DefineDOMInterface::<TH>),
        (b"VRDisplayCapabilities" as &'static [u8], codegen::Bindings::VRDisplayCapabilitiesBinding::VRDisplayCapabilitiesBinding::DefineDOMInterface::<TH>),
        (b"WorkerGlobalScope" as &'static [u8], codegen::Bindings::WorkerGlobalScopeBinding::WorkerGlobalScopeBinding::DefineDOMInterface::<TH>),
        (b"HTMLTrackElement" as &'static [u8], codegen::Bindings::HTMLTrackElementBinding::HTMLTrackElementBinding::DefineDOMInterface::<TH>),
        (b"HashChangeEvent" as &'static [u8], codegen::Bindings::HashChangeEventBinding::HashChangeEventBinding::DefineDOMInterface::<TH>),
        (b"MediaQueryListEvent" as &'static [u8], codegen::Bindings::MediaQueryListEventBinding::MediaQueryListEventBinding::DefineDOMInterface::<TH>),
        (b"Storage" as &'static [u8], codegen::Bindings::StorageBinding::StorageBinding::DefineDOMInterface::<TH>),
        (b"RadioNodeList" as &'static [u8], codegen::Bindings::RadioNodeListBinding::RadioNodeListBinding::DefineDOMInterface::<TH>),
        (b"HTMLImageElement" as &'static [u8], codegen::Bindings::HTMLImageElementBinding::HTMLImageElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLFormElement" as &'static [u8], codegen::Bindings::HTMLFormElementBinding::HTMLFormElementBinding::DefineDOMInterface::<TH>),
        (b"CSSViewportRule" as &'static [u8], codegen::Bindings::CSSViewportRuleBinding::CSSViewportRuleBinding::DefineDOMInterface::<TH>),
        (b"HTMLOutputElement" as &'static [u8], codegen::Bindings::HTMLOutputElementBinding::HTMLOutputElementBinding::DefineDOMInterface::<TH>),
        (b"CSSRuleList" as &'static [u8], codegen::Bindings::CSSRuleListBinding::CSSRuleListBinding::DefineDOMInterface::<TH>),
        (b"Response" as &'static [u8], codegen::Bindings::ResponseBinding::ResponseBinding::DefineDOMInterface::<TH>),
        (b"HTMLBRElement" as &'static [u8], codegen::Bindings::HTMLBRElementBinding::HTMLBRElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLHeadElement" as &'static [u8], codegen::Bindings::HTMLHeadElementBinding::HTMLHeadElementBinding::DefineDOMInterface::<TH>),
        (b"DOMPointReadOnly" as &'static [u8], codegen::Bindings::DOMPointReadOnlyBinding::DOMPointReadOnlyBinding::DefineDOMInterface::<TH>),
        (b"StorageEvent" as &'static [u8], codegen::Bindings::StorageEventBinding::StorageEventBinding::DefineDOMInterface::<TH>),
        (b"CSSNamespaceRule" as &'static [u8], codegen::Bindings::CSSNamespaceRuleBinding::CSSNamespaceRuleBinding::DefineDOMInterface::<TH>),
        (b"Range" as &'static [u8], codegen::Bindings::RangeBinding::RangeBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableRowElement" as &'static [u8], codegen::Bindings::HTMLTableRowElementBinding::HTMLTableRowElementBinding::DefineDOMInterface::<TH>),
        (b"CSSRule" as &'static [u8], codegen::Bindings::CSSRuleBinding::CSSRuleBinding::DefineDOMInterface::<TH>),
        (b"Comment" as &'static [u8], codegen::Bindings::CommentBinding::CommentBinding::DefineDOMInterface::<TH>),
        (b"CSSStyleRule" as &'static [u8], codegen::Bindings::CSSStyleRuleBinding::CSSStyleRuleBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableColElement" as &'static [u8], codegen::Bindings::HTMLTableColElementBinding::HTMLTableColElementBinding::DefineDOMInterface::<TH>),
        (b"Worker" as &'static [u8], codegen::Bindings::WorkerBinding::WorkerBinding::DefineDOMInterface::<TH>),
        (b"BeforeUnloadEvent" as &'static [u8], codegen::Bindings::BeforeUnloadEventBinding::BeforeUnloadEventBinding::DefineDOMInterface::<TH>),
        (b"Gamepad" as &'static [u8], codegen::Bindings::GamepadBinding::GamepadBinding::DefineDOMInterface::<TH>),
        (b"HTMLProgressElement" as &'static [u8], codegen::Bindings::HTMLProgressElementBinding::HTMLProgressElementBinding::DefineDOMInterface::<TH>),
        (b"XMLHttpRequest" as &'static [u8], codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestBinding::DefineDOMInterface::<TH>),
        (b"WebGLUniformLocation" as &'static [u8], codegen::Bindings::WebGLUniformLocationBinding::WebGLUniformLocationBinding::DefineDOMInterface::<TH>),
        (b"InputEvent" as &'static [u8], codegen::Bindings::InputEventBinding::InputEventBinding::DefineDOMInterface::<TH>),
        (b"CanvasGradient" as &'static [u8], codegen::Bindings::CanvasGradientBinding::CanvasGradientBinding::DefineDOMInterface::<TH>),
        (b"ImageData" as &'static [u8], codegen::Bindings::ImageDataBinding::ImageDataBinding::DefineDOMInterface::<TH>),
        (b"HTMLLegendElement" as &'static [u8], codegen::Bindings::HTMLLegendElementBinding::HTMLLegendElementBinding::DefineDOMInterface::<TH>),
        (b"Text" as &'static [u8], codegen::Bindings::TextBinding::TextBinding::DefineDOMInterface::<TH>),
        (b"HTMLStyleElement" as &'static [u8], codegen::Bindings::HTMLStyleElementBinding::HTMLStyleElementBinding::DefineDOMInterface::<TH>),
        (b"PerformanceEntry" as &'static [u8], codegen::Bindings::PerformanceEntryBinding::PerformanceEntryBinding::DefineDOMInterface::<TH>),
        (b"BluetoothRemoteGATTDescriptor" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTDescriptorBinding::BluetoothRemoteGATTDescriptorBinding::DefineDOMInterface::<TH>),
        (b"DOMException" as &'static [u8], codegen::Bindings::DOMExceptionBinding::DOMExceptionBinding::DefineDOMInterface::<TH>),
        (b"BluetoothPermissionResult" as &'static [u8], codegen::Bindings::BluetoothPermissionResultBinding::BluetoothPermissionResultBinding::DefineDOMInterface::<TH>),
        (b"CSSStyleValue" as &'static [u8], codegen::Bindings::CSSStyleValueBinding::CSSStyleValueBinding::DefineDOMInterface::<TH>),
        (b"DedicatedWorkerGlobalScope" as &'static [u8], codegen::Bindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScopeBinding::DefineDOMInterface::<TH>),
        (b"UIEvent" as &'static [u8], codegen::Bindings::UIEventBinding::UIEventBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableCellElement" as &'static [u8], codegen::Bindings::HTMLTableCellElementBinding::HTMLTableCellElementBinding::DefineDOMInterface::<TH>),
        (b"WebGLActiveInfo" as &'static [u8], codegen::Bindings::WebGLActiveInfoBinding::WebGLActiveInfoBinding::DefineDOMInterface::<TH>),
        (b"StyleSheet" as &'static [u8], codegen::Bindings::StyleSheetBinding::StyleSheetBinding::DefineDOMInterface::<TH>),
        (b"TestBinding" as &'static [u8], codegen::Bindings::TestBindingBinding::TestBindingBinding::DefineDOMInterface::<TH>),
        (b"WorkerLocation" as &'static [u8], codegen::Bindings::WorkerLocationBinding::WorkerLocationBinding::DefineDOMInterface::<TH>),
        (b"DOMRect" as &'static [u8], codegen::Bindings::DOMRectBinding::DOMRectBinding::DefineDOMInterface::<TH>),
        (b"HTMLParagraphElement" as &'static [u8], codegen::Bindings::HTMLParagraphElementBinding::HTMLParagraphElementBinding::DefineDOMInterface::<TH>),
        (b"ProgressEvent" as &'static [u8], codegen::Bindings::ProgressEventBinding::ProgressEventBinding::DefineDOMInterface::<TH>),
        (b"BluetoothRemoteGATTService" as &'static [u8], codegen::Bindings::BluetoothRemoteGATTServiceBinding::BluetoothRemoteGATTServiceBinding::DefineDOMInterface::<TH>),
        (b"DOMImplementation" as &'static [u8], codegen::Bindings::DOMImplementationBinding::DOMImplementationBinding::DefineDOMInterface::<TH>),
        (b"SVGSVGElement" as &'static [u8], codegen::Bindings::SVGSVGElementBinding::SVGSVGElementBinding::DefineDOMInterface::<TH>),
        (b"WebGLFramebuffer" as &'static [u8], codegen::Bindings::WebGLFramebufferBinding::WebGLFramebufferBinding::DefineDOMInterface::<TH>),
        (b"HTMLTableElement" as &'static [u8], codegen::Bindings::HTMLTableElementBinding::HTMLTableElementBinding::DefineDOMInterface::<TH>),
        (b"VRDisplayEvent" as &'static [u8], codegen::Bindings::VRDisplayEventBinding::VRDisplayEventBinding::DefineDOMInterface::<TH>),
        (b"HTMLTemplateElement" as &'static [u8], codegen::Bindings::HTMLTemplateElementBinding::HTMLTemplateElementBinding::DefineDOMInterface::<TH>),
        (b"TextDecoder" as &'static [u8], codegen::Bindings::TextDecoderBinding::TextDecoderBinding::DefineDOMInterface::<TH>),
        (b"Blob" as &'static [u8], codegen::Bindings::BlobBinding::BlobBinding::DefineDOMInterface::<TH>),
        (b"HTMLElement" as &'static [u8], codegen::Bindings::HTMLElementBinding::HTMLElementBinding::DefineDOMInterface::<TH>),
        (b"CSSGroupingRule" as &'static [u8], codegen::Bindings::CSSGroupingRuleBinding::CSSGroupingRuleBinding::DefineDOMInterface::<TH>),
        (b"HTMLMeterElement" as &'static [u8], codegen::Bindings::HTMLMeterElementBinding::HTMLMeterElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLDListElement" as &'static [u8], codegen::Bindings::HTMLDListElementBinding::HTMLDListElementBinding::DefineDOMInterface::<TH>),
        (b"DOMRectReadOnly" as &'static [u8], codegen::Bindings::DOMRectReadOnlyBinding::DOMRectReadOnlyBinding::DefineDOMInterface::<TH>),
        (b"TestBindingProxy" as &'static [u8], codegen::Bindings::TestBindingProxyBinding::TestBindingProxyBinding::DefineDOMInterface::<TH>),
        (b"FileReaderSync" as &'static [u8], codegen::Bindings::FileReaderSyncBinding::FileReaderSyncBinding::DefineDOMInterface::<TH>),
        (b"TestWorklet" as &'static [u8], codegen::Bindings::TestWorkletBinding::TestWorkletBinding::DefineDOMInterface::<TH>),
        (b"NodeFilter" as &'static [u8], codegen::Bindings::NodeFilterBinding::NodeFilterBinding::DefineDOMInterface::<TH>),
        (b"PageTransitionEvent" as &'static [u8], codegen::Bindings::PageTransitionEventBinding::PageTransitionEventBinding::DefineDOMInterface::<TH>),
        (b"FocusEvent" as &'static [u8], codegen::Bindings::FocusEventBinding::FocusEventBinding::DefineDOMInterface::<TH>),
        (b"Navigator" as &'static [u8], codegen::Bindings::NavigatorBinding::NavigatorBinding::DefineDOMInterface::<TH>),
        (b"HTMLLinkElement" as &'static [u8], codegen::Bindings::HTMLLinkElementBinding::HTMLLinkElementBinding::DefineDOMInterface::<TH>),
        (b"DOMStringMap" as &'static [u8], codegen::Bindings::DOMStringMapBinding::DOMStringMapBinding::DefineDOMInterface::<TH>),
        (b"Event" as &'static [u8], codegen::Bindings::EventBinding::EventBinding::DefineDOMInterface::<TH>),
        (b"URLSearchParams" as &'static [u8], codegen::Bindings::URLSearchParamsBinding::URLSearchParamsBinding::DefineDOMInterface::<TH>),
        (b"ExtendableMessageEvent" as &'static [u8], codegen::Bindings::ExtendableMessageEventBinding::ExtendableMessageEventBinding::DefineDOMInterface::<TH>),
        (b"HTMLMetaElement" as &'static [u8], codegen::Bindings::HTMLMetaElementBinding::HTMLMetaElementBinding::DefineDOMInterface::<TH>),
        (b"Image" as &'static [u8], codegen::Bindings::HTMLImageElementBinding::HTMLImageElementBinding::DefineDOMInterface::<TH>),
        (b"TransitionEvent" as &'static [u8], codegen::Bindings::TransitionEventBinding::TransitionEventBinding::DefineDOMInterface::<TH>),
        (b"HTMLTimeElement" as &'static [u8], codegen::Bindings::HTMLTimeElementBinding::HTMLTimeElementBinding::DefineDOMInterface::<TH>),
        (b"VRFrameData" as &'static [u8], codegen::Bindings::VRFrameDataBinding::VRFrameDataBinding::DefineDOMInterface::<TH>),
        (b"HTMLHRElement" as &'static [u8], codegen::Bindings::HTMLHRElementBinding::HTMLHRElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLOptionsCollection" as &'static [u8], codegen::Bindings::HTMLOptionsCollectionBinding::HTMLOptionsCollectionBinding::DefineDOMInterface::<TH>),
        (b"PaintRenderingContext2D" as &'static [u8], codegen::Bindings::PaintRenderingContext2DBinding::PaintRenderingContext2DBinding::DefineDOMInterface::<TH>),
        (b"ValidityState" as &'static [u8], codegen::Bindings::ValidityStateBinding::ValidityStateBinding::DefineDOMInterface::<TH>),
        (b"History" as &'static [u8], codegen::Bindings::HistoryBinding::HistoryBinding::DefineDOMInterface::<TH>),
        (b"HTMLFontElement" as &'static [u8], codegen::Bindings::HTMLFontElementBinding::HTMLFontElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLOListElement" as &'static [u8], codegen::Bindings::HTMLOListElementBinding::HTMLOListElementBinding::DefineDOMInterface::<TH>),
        (b"HTMLOptGroupElement" as &'static [u8], codegen::Bindings::HTMLOptGroupElementBinding::HTMLOptGroupElementBinding::DefineDOMInterface::<TH>),
        (b"StylePropertyMapReadOnly" as &'static [u8], codegen::Bindings::StylePropertyMapReadOnlyBinding::StylePropertyMapReadOnlyBinding::DefineDOMInterface::<TH>),
        (b"WorkerNavigator" as &'static [u8], codegen::Bindings::WorkerNavigatorBinding::WorkerNavigatorBinding::DefineDOMInterface::<TH>),
        (b"XMLDocument" as &'static [u8], codegen::Bindings::XMLDocumentBinding::XMLDocumentBinding::DefineDOMInterface::<TH>),
    ]);
}

// Requires initialization using init_MAP, which provides condrete type based on TypeHolder
pub static mut MAP: phf::Map<&'static [u8], unsafe fn(*mut JSContext, HandleObject)> = ::phf::Map {
    key: 1897749892740154578,
    disps: ::phf::Slice::Static(&[
        (0, 31),
        (0, 1),
        (0, 16),
        (1, 142),
        (0, 4),
        (0, 118),
        (0, 56),
        (0, 9),
        (1, 13),
        (5, 256),
        (1, 169),
        (0, 10),
        (1, 5),
        (5, 162),
        (0, 184),
        (0, 14),
        (0, 0),
        (0, 130),
        (0, 9),
        (2, 86),
        (1, 255),
        (0, 28),
        (0, 55),
        (0, 21),
        (0, 34),
        (0, 146),
        (1, 21),
        (1, 0),
        (0, 1),
        (3, 92),
        (0, 52),
        (0, 0),
        (0, 150),
        (0, 26),
        (0, 225),
        (1, 17),
        (1, 92),
        (0, 6),
        (1, 28),
        (0, 17),
        (1, 2),
        (0, 245),
        (0, 199),
        (3, 205),
        (0, 17),
        (0, 182),
        (19, 26),
        (0, 68),
        (5, 239),
        (15, 181),
        (86, 236),
        (2, 145),
        (9, 199),
    ]),
    entries: ::phf::Slice::Static(&[]),
};
