/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

use dom::bindings::codegen;
use js::jsapi::JSContext;
use js::rust::HandleObject;
use phf;
use typeholder::TypeHolderTrait;

bitflags! {
    pub struct Globals: u8 {
        const EMPTY = 0x0;
        const DEDICATED_WORKER_GLOBAL_SCOPE = 0x1;
        const DISSIMILAR_ORIGIN_WINDOW = 0x2;
        const PAINT_WORKLET_GLOBAL_SCOPE = 0x4;
        const SERVICE_WORKER_GLOBAL_SCOPE = 0x8;
        const TEST_WORKLET_GLOBAL_SCOPE = 0x10;
        const WINDOW = 0x20;
    }
}

include!("./InterfaceObjectMapPhf.rs");